apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: crud-ms
data:
  application.properties: |
    server.port=8080
    spring.jpa.database=postgresql
    spring.datasource.url=jdbc:postgresql://postgres/postgres
    spring.datasource.username=${PS_USERNAME}
    spring.datasource.password=${PS_PASSWORD}
    spring.jpa.generate-ddl=true
    spring.jpa.hibernate.ddl-auto=update
    jwt.issuer=crud-ms
    jwt.secret=${JWT_SECRET}
    jwt.auth-expiration-time=100000
    jwt.refresh-expiration-time=1000000

    # Enabling Kubernetes
    spring.cloud.kubernetes.enabled=true
    spring.cloud.kubernetes.ribbon.enabled=true
    spring.cloud.kubernetes.discovery.enabled=true
    spring.cloud.kubernetes.config.enabled=true

    #Disabling Eureka
    eureka.client.enabled=false