apiVersion: apps/v1
kind: Deployment
metadata:
  name: capser-backend
  namespace: capser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capser-backend
  template:
    metadata:
      labels:
        app: capser-backend
    spec:
      containers:
        - name: capser-backend
          image: aether97/capser:backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PS_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: db-secret
            - name: PS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-secret
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: jwtt-secret
      imagePullSecrets:
        - name: regcred
