kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pv-claim
  labels:
    app: mongodb
  namespace: crud-ms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
