kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
  namespace: capser
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
