package com.mwozniak.capser_v2.ytremote.enums;

public enum MessageType {
    ERROR, START, STOP, MEDIA_CONTROL, SET_RECEIVER, RECEIVERS, CONTROLS_SONG, CONTROLS_TIME, CONTROLS_DETAILS,
    CURRENT_RECEIVER, QUEUE, QUEUE_LENGTH, HEART_BEAT, QUEUE_CONTROL, HOME, SEARCH_CONTROL
}
